# This is a basic workflow to help you get started with Actions

name: tar_docker_image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # docker pull --platform linux/arm64 <image_name:tag>
      - name: Pull Docker image
        run: |
          docker pull --platform linux/arm64 nodered/node-red:3.1.15
          docker images  # 验证镜像已拉取

      # run: docker save <image_name> -o <tar_name>
      - name: Save image as .tar file
        run: docker save nodered/node-red:3.1.15 -o nodered-arm64.tar

      - name: Upload .tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodered-arm64.tar
          path: nodered-arm64.tar
